-- Add images to The Punjabi House menu items
UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1626082927389-6cd097cda1ec?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Paneer Tikka', 'Peri Peri Paneer Tikka', 'Afghani Malai Paneer Tikka', 'Achari Paneer Tikka', 'Lemon Paneer Tikka', 'Lemon Chaap Tikka', 'Peri Peri Chaap Tikka', 'Delhi Soya Chaap Tikka', 'Afghani Malai Soya Chaap', 'Dahi Kebab', 'Veg Tandoori Platter', 'Paneer Chilly', 'Paneer Manchurian', 'Dragon Paneer', 'Paneer Majestic', 'Paneer Pepper Dry', 'Paneer 65', 'Lemon Paneer');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1599603810694-e6e99eaf27fa?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Tandoori Mushroom', 'Hara Bhara Kebab', 'Honey Chilly Potato', 'Crispy Corn', 'Veg Manchurian', 'Crispy Chilli Potato', 'Gobi Manchurian / Chilly', 'Gobi Pepper Dry / 65', 'Mushroom Manchurian / Chilly', 'Mushroom Pepper Dry', 'Babycorn Manchurian / Chilly', 'Babycorn Pepper Dry');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Chicken Tikka', 'Boneless Chicken Tikka', 'Afghani Malai Chicken Tikka', 'Garlic Chicken Tikka', 'Lemon Chicken Tikka', 'Chicken Sheek Kebab', 'Chicken Reshmi Kebab', 'Chicken Tangri Kebab', 'Patiala Tangri Kebab', 'Afghani Tangri Kebab', 'Chicken Tandoori Platter', 'Drums of Heaven', 'Lollipop (Chilly/Manchurian)', 'Chicken Kali Mirch Andhra Special', 'Dragon Chicken', 'Chicken Majestic', 'Chilly Chicken', 'Chicken Manchurian', 'Lemon Chicken', 'Chicken 65', 'Chicken Pepper Dry', 'Garlic Chicken', 'Chicken Fry Kebab');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Egg Chilly', 'Egg Manchurian', 'Egg Pepper Dry', 'Egg 65', 'Egg Bhurji', 'Masala Omelette', 'Plain Omelette', 'Masala Boiled Eggs', 'Boiled Eggs');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Masala Papad', 'Roasted / Fry Papad', 'Dal Bhadi Raita', 'Veg / Boondi Raita', 'Green Salad', 'Veg Manchow Soup', 'Veg Hot & Sour Soup', 'Tomato Soup', 'Lemon Coriander Soup', 'Chicken Manchow Soup', 'Chicken Hot & Sour Soup', 'Chicken Clear Soup', 'Lemon Coriander Chicken Soup');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1601050915917-f3f88e0055be?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Paneer Tikka Masala', 'Paneer Takatak', 'Rara Paneer', 'Paneer Tawa', 'Amritsari Paneer Masala', 'Kadhai Paneer', 'Shahi Paneer', 'Punjabi Paneer', 'Paneer Kolhapuri', 'Palak Paneer', 'Paneer Do Pyaza', 'Matar Paneer', 'Paneer Pasanda', 'Kaju Paneer', 'Paneer Bhurji', 'Malai Paneer Kofta', 'Veg Kofta', 'Paneer Kofta', 'Dal Makhani', 'Special Dhaba Style Dal', 'Ghee Dal Tadka', 'Dal Fry', 'Mushroom Tikka Masala', 'Mushroom Masala', 'Matar Mushroom', 'Kadhai Mushroom', 'Chaap Tikka Masala', 'Tawa Chaap', 'Chaap Butter Masala', 'Punjabi Chaap Masala', 'Shahi Chaap Masala', 'Kali Masala', 'Kaju Kolhapuri', 'Veg Jalfrezi', 'Rajma Masala', 'Punjabi Kadhi Pakoda', 'Chana Masala', 'Chana Paneer Masala', 'Aloo Gobi Matar', 'Aloo Jeera - Dry', 'Bhindi Fry - Dry', 'Bhindi Masala', 'Mix Veg', 'Veg Kadhai', 'Veg Kolhapuri', 'Veg Nizami Handi', 'Tawa Veg', 'Green Peas Masala');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Signature Delhi Butter Chicken', 'Tandoori Chicken Masala', 'Chicken Tikka Masala', 'Punjabi Chicken Masala', 'Pind''s Fav- Rara Chicken', 'Special Chicken Takatak', 'Dhaba Style Kadhai Chicken', 'Chicken Kolhapuri', 'Mughlai Chicken Labaddar', 'Patiala Dalak Chicken', 'Afghani Malai Chicken', 'Nawabi Chicken Korma', 'Dhaba Chicken Masala', 'Chicken Kali Mirch', 'Homestyle Chicken Curry', 'Egg Punjabi Masala', 'Egg Kadhai', 'Egg Kolhapuri', 'Dhaba Egg Masala', 'Egg Curry', 'Mutton Rogan Josh', 'Rara Mutton', 'Mutton Kadhai', 'Mutton Masala');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1596379957409-a3a5c67df32f?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Plain Phulka', 'Butter Phulka', 'Desi Ghee Phulka', 'Plain Tandoori Roti', 'Butter Tandoori Roti', 'Bread Basket', 'Garlic Laccha Paratha', 'SPL Laccha Paratha', 'Kerela Paratha', 'Tawa Paratha', 'Ajwain Paratha', 'Rumali Roti', 'Aloo Paratha', 'Pyaaz Paratha', 'Aloo Pyaaz Paratha', 'Paneer Paratha', 'Gobi Paratha');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1585521537196-7b0de6c7fbe8?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Cheese Garlic Naan', 'Cheese Naan', 'Garlic Naan', 'Butter Naan', 'Plain Naan', 'Aloo Pyaaz Chur Naan', 'Paneer Chur Chur Naan', 'Cheese Kulcha', 'Butter Kulcha', 'Plain Kulcha', 'Paneer Kulcha', 'Aloo Pyaaz Kulcha', 'Amritsari Kulcha');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Veg Chowmein', 'Veg Noodles', 'Manchurian Noodles', 'Gobi Noodles', 'Pepper Noodles', 'Mushroom Noodles', 'Chilli Garlic Noodles', 'Chicken Chowmein', 'Chicken Noodles', 'Schezwan Chicken Noodles', 'Chilli Garlic Chicken Noodles', 'Egg Noodles', 'Egg Schezwan Noodles', 'Egg Chilli Garlic Noodles');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1609501676725-7186f017a4b2?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name IN ('Veg Fried Rice', 'Manchurian Fried Rice', 'Gobi Fried Rice', 'Paneer Fried Rice', 'Mushroom Fried Rice', 'Chilli Garlic Rice', 'Chicken Fried Rice', 'Schezwan Chicken Fried Rice', 'Chilli Garlic Chicken Rice', 'Egg Fried Rice', 'Egg Schezwan Fried Rice', 'Egg Chilli Garlic Fried Rice', 'Steam Rice', 'Jeera Rice', 'Ghee Rice', 'Dal Khichdi', 'Palak Khichdi', 'Masala Rice', 'Paneer Pulav', 'Veg Pulav', 'Green Peas Pulav', 'Curd Rice');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929314c3fe6?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name LIKE '%Biryani%';

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND (name LIKE '%Thali%' OR name LIKE '%Combo%' OR name LIKE '%Bowl%' OR name LIKE '%Bhature%');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND (name LIKE '%Fries%' OR name = 'Salted Fries' OR name = 'Cheesy Fries' OR name = 'Paneer Tikka Loaded Fries' OR name = 'Chicken Tikka Loaded Fries');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1621996346565-431f63602f41?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND name LIKE '%Pasta%';

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND (name LIKE '%Lassi%' OR name = 'Butter Milk');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND (name = 'Choco Lava Cake' OR name = 'Walnut Brownie');

UPDATE cafeteria_menu SET image_url = 'https://images.unsplash.com/photo-1551632440-e5e89f63c076?w=200&h=200&fit=crop' WHERE (SELECT id FROM cafeterias WHERE name = 'The Punjabi House' LIMIT 1) = cafeteria_id AND (name = 'Gulab Jamun' OR name = 'Matka Rabdi' OR name = 'Rasmalai');
